# docker-compose.yaml
version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        tty: true
        depends_on:
            - db
        networks:
            - app-network
        ports:
            - "8080:8080"
        environment:
            DB_MAIN_ADDRESS: db
            DB_MAIN_PORT: 5432
            DB_MAIN_USERNAME: user
            DB_MAIN_PASSWORD: pass

    db:
        image: postgres:12
        container_name: db
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: devdb
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "54320:5432"

volumes:
    db_data:

networks:
    app-network:
